FROM my/sensority-dev

RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/libexec/sftp-server'; \
  ) > /etc/ssh/sshd-sensority-remote-dev \
  && mkdir /run/sshd

RUN useradd -m user && yes password | passwd user
RUN usermod -s /bin/bash user
RUN ssh-keygen -A

CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd-sensority-remote-dev"]