FROM my/sensority

ARG USERNAME=user
ARG UID=1000
ARG GID=1000

RUN groupdel $USERNAME || true
RUN userdel -r -f $USERNAME || true && rm -rf /home/$USERNAME
RUN groupadd -f -g $GID $USERNAME
RUN useradd -l -g $GID -u $UID -ms /bin/bash $USERNAME
RUN echo $USERNAME:$USERNAME | chpasswd
RUN echo '$USERNAME ALL=(ALL) NOPASSWD:SETENV: ALL' > /etc/sudoers.d/$USERNAME || true

USER $USERNAME
CMD ["/bin/bash"]